<?php

/**
 * Custom Delete Module
 */

/**
 * Implementation of hook_menu()
 */
function custom_delete_menu() {
  $items['custom/delete'] = array(
    'title' => 'Delete Nodes',
    'page callback' => 'custom_delete_page',
    'access arguments' => array('administer content'),
    'type' => MENU_CALLBACK,
  );

  $items['custom/delete/%'] = array(
    'title' => 'Delete Nodes',
    'page callback' => 'custom_delete_delete_node',
    'page arguments' => array(2),
    'access arguments' => array('administer content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Page callback for custom/delete
 */
function custom_delete_page() {
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
    ->range(0, 10);

  $result = $query->execute();

  if (isset($result['node'])) {
    $node_nids = array_keys($result['node']);
    $nodes = entity_load('node', $node_nids);
  }

  $header = array('Node ID', 'Title', 'Delete');
  $rows = array();
  foreach ($nodes as $nid => $node) {
    $rows[] = array($node->nid, $node->title, l('Delete', 'custom/delete/' . $node->nid));
  }

  return theme('table', array('header' => $header, 'rows' => $rows));
}

/**
 * Page callback for custom/delete/%
 */
function custom_delete_delete_node($nid) {
  node_delete($nid);

  drupal_set_message('Node #' . $nid . ' Deleted');
  drupal_goto();
}